# Generated by Django 4.2.14 on 2024-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amort', '0002_loanoffer_interestrate_loanoffer_loanperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='interestRate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
