# Generated by Django 4.2.14 on 2024-07-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amort', '0003_alter_loanoffer_interestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoffer',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amort.customer'),
            preserve_default=False,
        ),
    ]
